# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[25,)" #mandatory (24 is current forge version)

issueTrackerURL="https://github.com/Sinhika/Netherrocks/issues"

[[mods]]
modId="simple_netherrocks"
version="${version}"
displayName="SimpleOres:Netherrocks"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/Netherrocks/1.14/update.json"
displayURL="http://minecraft.curseforge.com/projects/netherrocks"
logoFile=""
credits="Thanks to AleXndrTheGr8st for creating the original mod and to Sinhika for porting and maintaining it."
authors="AleXndrTheGr8st, Sinhika"
description='''
'''

[[dependencies.simple_netherrocks]] #optional
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simple_netherrocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"