# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory
issueTrackerURL="https://github.com/Sinhika/Netherrocks/issues"
license="${mod_license}"
logoFile="netherrocks.png"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/Netherrocks/1.20/update.json"
displayURL="http://minecraft.curseforge.com/projects/netherrocks"
credits="AleXndrTheGr8st (original mod), Sinhika (ports, maintenance) and Wuppy29 (Ghast Ore idea from Peaceful Pack)"
authors="${mod_authors}"
description='''
Adds 6 more ores to the base game that are found only in the Nether: Argonite, Ashstone, Dragonstone, Fyrite, Illumenite, and Malachite. Each ore has its own unique properties, armor and tool sets, and more.

Additional Credits: AzazEL3095 (Spanish translation)
'''

[[dependencies.${mod_id}]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

 [[dependencies.${mod_id}]]
    modId="simplecorelib"
    mandatory=true
    versionRange="${simplecore_range}"
    ordering="NONE"
    side="BOTH"
    
# [[dependencies.${mod_id}]]
#         modId="silents_mechanisms"
#         mandatory=false
#         versionRange="[0.8.9,)"
#         ordering="BEFORE"
#         side="BOTH"
#         
# [[dependencies.${mod_id}]]
#         modId="silentgear"
#         mandatory=false
#         versionRange="[2.5.2,)"
#         ordering="BEFORE"
#         side="BOTH"
