# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/Netherrocks/issues"
license="LGPL 3.0"
logoFile="netherrocks.png"

[[mods]]
modId="netherrocks"
version="${file.jarVersion}"
displayName="SimpleOres:Netherrocks"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/Netherrocks/1.16/update.json"
displayURL="http://minecraft.curseforge.com/projects/netherrocks"
credits="AleXndrTheGr8st (original mod) and Sinhika (ports, maintenance)"
authors="AleXndrTheGr8st, Sinhika"
description='''
Adds 6 more ores to the base game that are found only in the Nether: Argonite, Ashstone, Dragonstone, Fyrite, Illumenite, and Malachite. Each ore has its own unique properties, armor and tool sets, and more.

Additional Credits: AzazEL3095 (Spanish translation)
'''

[[dependencies.netherrocks]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.netherrocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

 [[dependencies.netherrocks]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.16.5-2.0.8.0,1.16.5-2.0.9.0)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.netherrocks]]
        modId="silents_mechanisms"
        mandatory=false
        versionRange="[0.8.9,)"
        ordering="BEFORE"
        side="BOTH"
        
[[dependencies.netherrocks]]
        modId="silentgear"
        mandatory=false
        versionRange="[2.5.2,)"
        ordering="BEFORE"
        side="BOTH"
